public class Map_Pra
{
    //prmitive datype
    
    //Integer****
    //Decimal
    //String********
    //Boolean(t/f)-mostly if and else block rarely will use in dowhile and while
    //Long
    //Double
    //Blob
    //Object (universal datatype)
    //Date************
    //Datetime
    //time
    
    
    Public Void Main()
    {
        
    }
    Void M_dEC()
    {
        //List Declaration  //primivite datatype //sobject //apexclass //triggers //vffage //auracomponenet
        
        //Syntax of List
        //List<Primitive_data_type> <variable> = new List<Primitive_data_type>();
        
        //integer
        List<Integer> kishore = new List<Integer>();
        //how to add values in the list 
        //1st way to add values
          kishore.add(10);
          kishore.add(30);
          kishore.add(50);
        system.debug('The list of elements are '+kishore);
        
        

    }

}