public virtual class MultiClassA
{
    Public Void Add()
    {
        Integer i = 10;
        Integer j = 20;
        Integer k = 30;
        Integer res = i+j+k;
        system.debug('The add function is'+res);
    }
   Public Void Sub()
   {
       Integer i = 10;
        Integer j = 20;
        Integer k = 30;
        Integer res = i-j-k;
        system.debug('The sub '+res);
    }
   
    Public Void Mul()
    {
        Integer i = 10;
        Integer j = 20;
        Integer k = 30;
        Integer res = i*j*k;
        system.debug('The mul'+res);
        
    }
}