public class Ps {
   
    
    
    public void Add()
    {
       integer i = 10;
        integer j = 20;
        integer res;
        res = i+j;
   system.debug('The res of add is '+res);
        
        
        if(res>20)
        {
            Account a = new Account();
            a.Name = 'zakir';
            a.Phone = '6677';
            a.AnnualRevenue = 898;
            insert a;
            
            
        }
        else
        {
            system.debug('No result is >20');
        }
               
    }
   
   
    
    
    
    

}