public class ScheduleAPEX 
{
    //it has one method called exceute method it will schedule at regular intervals
   
    //schedule job is exceuted apex code cant be modified
    
    //we can delete scheducle job first then we need to modify the apex code
    
    //we can write apex class with exceute method and that method will be sheducle in future at regular intervals
    
    //schdule apex will be done through cron expression
    
    

}